(define (problem fix_scene)
  (:domain office)
  (:objects
    agent1 - agent
    room_initial room_target - room
    bottle_0 bottle_1 bottle_2 bottle_3 bottle_4 - item
  )
  (:init
    (agent_at agent1 room_initial)
    (neighbor room_initial room_target)
    (neighbor room_target room_initial)
    (item_at bottle_0 room_initial)
    (item_at bottle_1 room_initial)
    (item_at bottle_2 room_initial)
    (item_at bottle_3 room_initial)
    (item_at bottle_4 room_initial)
    (can_accessible bottle_0)
    (can_graspable bottle_0)
    (can_liftable bottle_0)
    (can_accessible bottle_1)
    (can_graspable bottle_1)
    (can_liftable bottle_1)
    (can_accessible bottle_2)
    (can_graspable bottle_2)
    (can_liftable bottle_2)
    (can_accessible bottle_3)
    (can_graspable bottle_3)
    (can_liftable bottle_3)
    (can_accessible bottle_4)
    (can_graspable bottle_4)
    (can_liftable bottle_4)
  )
  (:goal (and (item_at bottle_0 room_target)
    (item_at bottle_1 room_target)
    (item_at bottle_2 room_target)
    (item_at bottle_3 room_target)
    (item_at bottle_4 room_target)))
)